# Generated by Django 6.1.1 on 2026-09-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100, verbose_name='Jméno')),
                ('prijmeni', models.CharField(max_length=100, verbose_name='Příjmení')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('pozice', models.CharField(max_length=100, verbose_name='Pracovní Pozice')),
            ],
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200, verbose_name='Název projektu')),
                ('popis', models.TextField(blank=True, verbose_name='Popis')),
                ('start_date', models.DateField(verbose_name='Datum zahájení')),
                ('end_date', models.DateField(blank=True, verbose_name='Datum ukončení')),
                ('stav', models.CharField(max_length=50, verbose_name='Stav projektu')),
                ('clenove', models.ManyToManyField(related_name='projekty', to='core.osoba', verbose_name='Členové týmu')),
            ],
        ),
    ]
