# Generated by Django 6.1.1 on 2026-09-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekt',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum ukončení'),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='nazev',
            field=models.CharField(max_length=200, unique=True, verbose_name='Název projektu'),
        ),
    ]
